var StylesObj={
    BackdropVisible:{
        display:'block',
        position:'fixed',
        top:0,
        left:0,
        right:0,
        bottom:0,
        width:'100%',
        height:'100vh',
        textAlign:'center'
    },
    LoaderHidden:{
        display:'none'
    },
    Modal:{
        display:'block',
        marginLeft:'auto',
        marginRight:'auto',
        width:300,
        borderRadius:'5px',
        marginTop:150,
        paddingTop:30,
        paddingBottom:30,
        textAlign:'center'
    },
    LoadingImage:{
        display:'block',
        width:50,
        marginLeft:'auto',
        marginRight:'auto',
        verticalAlign:'middle',
        marginBottom:30
    },
    LoadingText:{
        display:'block',
        width:'90%',
        marginLeft:'auto',
        marginRight:'auto',
        verticalAlign:'middle',
        marginTop:30,
        textAlign:'center'
    }
};

module.exports=StylesObj;